language: csharp
solution: csharp.dotnetcore.katas.simple.sln

sudo: required
dotnet: 1.0.4

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      mono: latest

branches:
  only:
    - master

script:
  - dotnet restore
  - dotnet test "tests\katas.basic.tests.csproj"
